policy documentation
vatsimnetwork/site-content pull request #3
Opened 2021-02-13 18:10 UTC by mbozwood

2021-02-17 22:45 UTC, doylemark requested changes
Great stuff, thanks this is very much appreciated, especially the CoC is 👌 .

2021-02-17 22:45 UTC, doylemark commented on policy/approved-software.mdx
> +Current as of 01NOV2019
Is this annotation still necessary? I feel this makes the site look somewhat "parked & abandoned". I think the reader should be able to assume all content on our website is up to date. The update date is recorded in our commit history anyway

2021-02-17 22:45 UTC, doylemark commented on policy/global-ratings-policy.mdx
> -1. Renewable for a total period of up to 90 days, with each renewal only to have a maximum period of validity of 30 days
Not that it matters much

2021-02-17 22:45 UTC, doylemark commented on policy/global-ratings-policy.mdx
> -* **6.8**   A list of all current EC approved Designated Airspace is attached as Appendix B to this policy.
Where is section 7 and below going?

2021-02-17 22:45 UTC, doylemark commented on policy/overview.mdx
> +---
Good content. I feel perhaps this page and the list of BOG meetings could due with a custom component of some kind, these long lists sometimes don't look the best. v1.1 perhaps

2021-02-23 15:21 UTC, mbozwood commented on policy/approved-software.mdx
> +Current as of 01NOV2019
It'll be updated in the coming weeks but I would say yes. I might event add a recent changes part to the page. 
It's not a date for us, you've rightly noted that we can see it it commit history but it's for others to see when things were last changed. I'll have a rethink on the page.

2021-02-23 15:26 UTC, doylemark commented on policy/approved-software.mdx
> +Current as of 01NOV2019
cool

2021-02-23 15:37 UTC, mbozwood commented on policy/global-ratings-policy.mdx
> -* **6.8**   A list of all current EC approved Designated Airspace is attached as Appendix B to this policy.
fixed in #2a59ca0

2021-02-23 17:19 UTC, doylemark reviewed
review complete

2021-02-23 17:20 UTC, doylemark reviewed
review complete

2021-02-23 17:20 UTC, doylemark approved these changes

2021-02-23 17:21 UTC, merged